spring:
  application:
    name: library
  h2:
    console:
      enabled: true

server:
  port: 8081

security:
  jwt:
    secret-key: 2E9vFBcJWgrcx3ciqI6TpUljf3k5pXQj2E9vFBcJWgrcx3ciqI6TpUljf3k5pXQj
    expiration: 86400000
    refresh-token:
      expiration: 604800000
